---
platform: linux

inputs:
- name: tile-src
- name: wf-nozzle-version

outputs:
- name: baked-tile

run:
  path: /bin/bash
  args:
  - -ceuf
  - |
    export root_dir="$(pwd)"
    cat wf-nozzle-version/version > "${root_dir}/tile-src/version.txt"
    curl -L https://github.com/cf-platform-eng/tile-generator/releases/download/v14.0.5/tile_linux-64bit -o tile
    chmod +x tile
    mv tile /usr/local/bin/
    pushd "${root_dir}/tile-src/"
      ./build.sh
    popd
    cp "${root_dir}"/tile-src/product/wavefront-nozzle-*.pivotal "${root_dir}/baked-tile"
