---
platform: linux

inputs:
- name: tile-src
- name: wf-nozzle-version

outputs:
- name: baked-tile

run:
  path: /bin/bash
  args:
  - -ceuf
  - |
    export root_dir=$(pwd)
    cat wf-nozzle-version/version > version.txt
    ${root_dir}/wf-nozzle/build.sh

